# Generated by Django 4.2.7 on 2023-11-28 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study_platform', '0003_course_num_lessons'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='num_lessons',
        ),
    ]
